- name: Configure webserver with nginx
  hosts: all
  become: True
  tasks:
    - name: install python3
      apt: name=python3 update_cache=yes

    - name: install nginx
      apt: name=nginx update_cache=yes

    - name: copy nginx config file
      copy: src=configs/nginx.conf dest=/etc/nginx/sites-available/default

    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link

    - name: copy index.html
      template: src=WebPage/index.html.j2 dest=/usr/share/nginx/html/index.html
        mode=0644

    - name: restart nginx
      service: name=nginx state=restarted